import { FAWaypointData, FAChestData } from './FAWaypointData';

// Auto-generated FA Initial State
export const INITIAL_FA_WAYPOINTS: Record<string, FAWaypointData> = {
  "stage_start": {
    "id": "stage_start",
    "state": "locked",
    "rankingPoints": 0,
    "chestIds": [
      "mpe_i_1_stage_start_1",
      "mpe_i_1_stage_start_2",
      "mpe_i_2_stage_start_1",
      "mpe_i_2_stage_start_2",
      "mpe_i_3_stage_start_1",
      "mpe_i_3_stage_start_2"
    ],
    "color": "start",
    "position": 0,
    "isMultiColored": false
  },
  "orange_2": {
    "id": "orange_2",
    "state": "locked",
    "rankingPoints": 0,
    "chestIds": [
      "mpe_i_1_orange_2_1",
      "mpe_i_1_orange_2_2",
      "mpe_i_1_orange_2_3",
      "mpe_i_2_orange_2_1",
      "mpe_i_2_orange_2_2",
      "mpe_i_2_orange_2_3",
      "mpe_i_3_orange_2_1",
      "mpe_i_3_orange_2_2",
      "mpe_i_3_orange_2_3"
    ],
    "color": "orange",
    "position": 2,
    "isMultiColored": false
  },
  "blue_2": {
    "id": "blue_2",
    "state": "locked",
    "rankingPoints": 0,
    "chestIds": [
      "mpe_i_1_blue_2_1",
      "mpe_i_1_blue_2_2",
      "mpe_i_1_blue_2_3",
      "mpe_i_2_blue_2_1",
      "mpe_i_2_blue_2_2",
      "mpe_i_2_blue_2_3",
      "mpe_i_3_blue_2_1",
      "mpe_i_3_blue_2_2",
      "mpe_i_3_blue_2_3"
    ],
    "color": "blue",
    "position": 2,
    "isMultiColored": false
  },
  "green_2": {
    "id": "green_2",
    "state": "locked",
    "rankingPoints": 0,
    "chestIds": [
      "mpe_i_1_green_2_1",
      "mpe_i_1_green_2_2",
      "mpe_i_1_green_2_3",
      "mpe_i_2_green_2_1",
      "mpe_i_2_green_2_2",
      "mpe_i_2_green_2_3",
      "mpe_i_3_green_2_1",
      "mpe_i_3_green_2_2",
      "mpe_i_3_green_2_3"
    ],
    "color": "green",
    "position": 2,
    "isMultiColored": false
  },
  "orange_3": {
    "id": "orange_3",
    "state": "locked",
    "rankingPoints": 0,
    "chestIds": [
      "mpe_i_1_orange_3_1",
      "mpe_i_1_orange_3_2",
      "mpe_i_1_orange_3_3",
      "mpe_i_2_orange_3_1",
      "mpe_i_2_orange_3_2",
      "mpe_i_2_orange_3_3",
      "mpe_i_3_orange_3_1",
      "mpe_i_3_orange_3_2",
      "mpe_i_3_orange_3_3"
    ],
    "color": "orange",
    "position": 3,
    "isMultiColored": true
  },
  "blue_3": {
    "id": "blue_3",
    "state": "locked",
    "rankingPoints": 0,
    "chestIds": [
      "mpe_i_1_blue_3_1",
      "mpe_i_1_blue_3_2",
      "mpe_i_1_blue_3_3",
      "mpe_i_2_blue_3_1",
      "mpe_i_2_blue_3_2",
      "mpe_i_2_blue_3_3",
      "mpe_i_3_blue_3_1",
      "mpe_i_3_blue_3_2",
      "mpe_i_3_blue_3_3"
    ],
    "color": "blue",
    "position": 3,
    "isMultiColored": true
  },
  "green_3": {
    "id": "green_3",
    "state": "locked",
    "rankingPoints": 0,
    "chestIds": [
      "mpe_i_1_green_3_1",
      "mpe_i_1_green_3_2",
      "mpe_i_1_green_3_3",
      "mpe_i_2_green_3_1",
      "mpe_i_2_green_3_2",
      "mpe_i_2_green_3_3",
      "mpe_i_3_green_3_1",
      "mpe_i_3_green_3_2",
      "mpe_i_3_green_3_3"
    ],
    "color": "green",
    "position": 3,
    "isMultiColored": true
  },
  "orange_4": {
    "id": "orange_4",
    "state": "locked",
    "rankingPoints": 0,
    "chestIds": [
      "mpe_i_1_orange_4_1",
      "mpe_i_1_orange_4_2",
      "mpe_i_1_orange_4_3",
      "mpe_i_2_orange_4_1",
      "mpe_i_2_orange_4_2",
      "mpe_i_2_orange_4_3",
      "mpe_i_3_orange_4_1",
      "mpe_i_3_orange_4_2",
      "mpe_i_3_orange_4_3"
    ],
    "color": "orange",
    "position": 4,
    "isMultiColored": false
  },
  "blue_4": {
    "id": "blue_4",
    "state": "locked",
    "rankingPoints": 0,
    "chestIds": [
      "mpe_i_1_blue_4_1",
      "mpe_i_1_blue_4_2",
      "mpe_i_1_blue_4_3",
      "mpe_i_2_blue_4_1",
      "mpe_i_2_blue_4_2",
      "mpe_i_2_blue_4_3",
      "mpe_i_3_blue_4_1",
      "mpe_i_3_blue_4_2",
      "mpe_i_3_blue_4_3"
    ],
    "color": "blue",
    "position": 4,
    "isMultiColored": false
  },
  "green_4": {
    "id": "green_4",
    "state": "locked",
    "rankingPoints": 0,
    "chestIds": [
      "mpe_i_1_green_4_1",
      "mpe_i_1_green_4_2",
      "mpe_i_1_green_4_3",
      "mpe_i_2_green_4_1",
      "mpe_i_2_green_4_2",
      "mpe_i_2_green_4_3",
      "mpe_i_3_green_4_1",
      "mpe_i_3_green_4_2",
      "mpe_i_3_green_4_3"
    ],
    "color": "green",
    "position": 4,
    "isMultiColored": false
  },
  "orange_5": {
    "id": "orange_5",
    "state": "locked",
    "rankingPoints": 0,
    "chestIds": [
      "mpe_i_1_orange_5_1",
      "mpe_i_1_orange_5_2",
      "mpe_i_1_orange_5_3",
      "mpe_i_2_orange_5_1",
      "mpe_i_2_orange_5_2",
      "mpe_i_2_orange_5_3",
      "mpe_i_3_orange_5_1",
      "mpe_i_3_orange_5_2",
      "mpe_i_3_orange_5_3"
    ],
    "color": "orange",
    "position": 5,
    "isMultiColored": false
  },
  "blue_5": {
    "id": "blue_5",
    "state": "locked",
    "rankingPoints": 0,
    "chestIds": [
      "mpe_i_1_blue_5_1",
      "mpe_i_1_blue_5_2",
      "mpe_i_1_blue_5_3",
      "mpe_i_2_blue_5_1",
      "mpe_i_2_blue_5_2",
      "mpe_i_2_blue_5_3",
      "mpe_i_3_blue_5_1",
      "mpe_i_3_blue_5_2",
      "mpe_i_3_blue_5_3"
    ],
    "color": "blue",
    "position": 5,
    "isMultiColored": false
  },
  "green_5": {
    "id": "green_5",
    "state": "locked",
    "rankingPoints": 0,
    "chestIds": [
      "mpe_i_1_green_5_1",
      "mpe_i_1_green_5_2",
      "mpe_i_1_green_5_3",
      "mpe_i_2_green_5_1",
      "mpe_i_2_green_5_2",
      "mpe_i_2_green_5_3",
      "mpe_i_3_green_5_1",
      "mpe_i_3_green_5_2",
      "mpe_i_3_green_5_3"
    ],
    "color": "green",
    "position": 5,
    "isMultiColored": false
  },
  "orange_6": {
    "id": "orange_6",
    "state": "locked",
    "rankingPoints": 0,
    "chestIds": [
      "mpe_i_1_orange_6_1",
      "mpe_i_1_orange_6_2",
      "mpe_i_1_orange_6_3",
      "mpe_i_2_orange_6_1",
      "mpe_i_2_orange_6_2",
      "mpe_i_2_orange_6_3",
      "mpe_i_3_orange_6_1",
      "mpe_i_3_orange_6_2",
      "mpe_i_3_orange_6_3"
    ],
    "color": "orange",
    "position": 6,
    "isMultiColored": true
  },
  "blue_6": {
    "id": "blue_6",
    "state": "locked",
    "rankingPoints": 0,
    "chestIds": [
      "mpe_i_1_blue_6_1",
      "mpe_i_1_blue_6_2",
      "mpe_i_1_blue_6_3",
      "mpe_i_2_blue_6_1",
      "mpe_i_2_blue_6_2",
      "mpe_i_2_blue_6_3",
      "mpe_i_3_blue_6_1",
      "mpe_i_3_blue_6_2",
      "mpe_i_3_blue_6_3"
    ],
    "color": "blue",
    "position": 6,
    "isMultiColored": true
  },
  "green_6": {
    "id": "green_6",
    "state": "locked",
    "rankingPoints": 0,
    "chestIds": [
      "mpe_i_1_green_6_1",
      "mpe_i_1_green_6_2",
      "mpe_i_1_green_6_3",
      "mpe_i_2_green_6_1",
      "mpe_i_2_green_6_2",
      "mpe_i_2_green_6_3",
      "mpe_i_3_green_6_1",
      "mpe_i_3_green_6_2",
      "mpe_i_3_green_6_3"
    ],
    "color": "green",
    "position": 6,
    "isMultiColored": true
  },
  "orange_7": {
    "id": "orange_7",
    "state": "locked",
    "rankingPoints": 0,
    "chestIds": [
      "mpe_i_1_orange_7_1",
      "mpe_i_1_orange_7_2",
      "mpe_i_1_orange_7_3",
      "mpe_i_2_orange_7_1",
      "mpe_i_2_orange_7_2",
      "mpe_i_2_orange_7_3",
      "mpe_i_3_orange_7_1",
      "mpe_i_3_orange_7_2",
      "mpe_i_3_orange_7_3"
    ],
    "color": "orange",
    "position": 7,
    "isMultiColored": false
  },
  "blue_7": {
    "id": "blue_7",
    "state": "locked",
    "rankingPoints": 0,
    "chestIds": [
      "mpe_i_1_blue_7_1",
      "mpe_i_1_blue_7_2",
      "mpe_i_1_blue_7_3",
      "mpe_i_2_blue_7_1",
      "mpe_i_2_blue_7_2",
      "mpe_i_2_blue_7_3",
      "mpe_i_3_blue_7_1",
      "mpe_i_3_blue_7_2",
      "mpe_i_3_blue_7_3"
    ],
    "color": "blue",
    "position": 7,
    "isMultiColored": false
  },
  "green_7": {
    "id": "green_7",
    "state": "locked",
    "rankingPoints": 0,
    "chestIds": [
      "mpe_i_1_green_7_1",
      "mpe_i_1_green_7_2",
      "mpe_i_1_green_7_3",
      "mpe_i_2_green_7_1",
      "mpe_i_2_green_7_2",
      "mpe_i_2_green_7_3",
      "mpe_i_3_green_7_1",
      "mpe_i_3_green_7_2",
      "mpe_i_3_green_7_3"
    ],
    "color": "green",
    "position": 7,
    "isMultiColored": false
  },
  "orange_8": {
    "id": "orange_8",
    "state": "locked",
    "rankingPoints": 0,
    "chestIds": [
      "mpe_i_1_orange_8_1",
      "mpe_i_1_orange_8_2",
      "mpe_i_1_orange_8_3",
      "mpe_i_2_orange_8_1",
      "mpe_i_2_orange_8_2",
      "mpe_i_2_orange_8_3",
      "mpe_i_3_orange_8_1",
      "mpe_i_3_orange_8_2",
      "mpe_i_3_orange_8_3"
    ],
    "color": "orange",
    "position": 8,
    "isMultiColored": false
  },
  "blue_8": {
    "id": "blue_8",
    "state": "locked",
    "rankingPoints": 0,
    "chestIds": [
      "mpe_i_1_blue_8_1",
      "mpe_i_1_blue_8_2",
      "mpe_i_1_blue_8_3",
      "mpe_i_2_blue_8_1",
      "mpe_i_2_blue_8_2",
      "mpe_i_2_blue_8_3",
      "mpe_i_3_blue_8_1",
      "mpe_i_3_blue_8_2",
      "mpe_i_3_blue_8_3"
    ],
    "color": "blue",
    "position": 8,
    "isMultiColored": false
  },
  "green_8": {
    "id": "green_8",
    "state": "locked",
    "rankingPoints": 0,
    "chestIds": [
      "mpe_i_1_green_8_1",
      "mpe_i_1_green_8_2",
      "mpe_i_1_green_8_3",
      "mpe_i_2_green_8_1",
      "mpe_i_2_green_8_2",
      "mpe_i_2_green_8_3",
      "mpe_i_3_green_8_1",
      "mpe_i_3_green_8_2",
      "mpe_i_3_green_8_3"
    ],
    "color": "green",
    "position": 8,
    "isMultiColored": false
  },
  "orange_9": {
    "id": "orange_9",
    "state": "locked",
    "rankingPoints": 0,
    "chestIds": [
      "mpe_i_1_orange_9_1",
      "mpe_i_1_orange_9_2",
      "mpe_i_1_orange_9_3",
      "mpe_i_2_orange_9_1",
      "mpe_i_2_orange_9_2",
      "mpe_i_2_orange_9_3",
      "mpe_i_3_orange_9_1",
      "mpe_i_3_orange_9_2",
      "mpe_i_3_orange_9_3"
    ],
    "color": "orange",
    "position": 9,
    "isMultiColored": false
  },
  "blue_9": {
    "id": "blue_9",
    "state": "locked",
    "rankingPoints": 0,
    "chestIds": [
      "mpe_i_1_blue_9_1",
      "mpe_i_1_blue_9_2",
      "mpe_i_1_blue_9_3",
      "mpe_i_2_blue_9_1",
      "mpe_i_2_blue_9_2",
      "mpe_i_2_blue_9_3",
      "mpe_i_3_blue_9_1",
      "mpe_i_3_blue_9_2",
      "mpe_i_3_blue_9_3"
    ],
    "color": "blue",
    "position": 9,
    "isMultiColored": false
  },
  "green_9": {
    "id": "green_9",
    "state": "locked",
    "rankingPoints": 0,
    "chestIds": [
      "mpe_i_1_green_9_1",
      "mpe_i_1_green_9_2",
      "mpe_i_1_green_9_3",
      "mpe_i_2_green_9_1",
      "mpe_i_2_green_9_2",
      "mpe_i_2_green_9_3",
      "mpe_i_3_green_9_1",
      "mpe_i_3_green_9_2",
      "mpe_i_3_green_9_3"
    ],
    "color": "green",
    "position": 9,
    "isMultiColored": false
  }
};

export const INITIAL_FA_CHESTS: Record<string, FAChestData> = {
  "mpe_i_1_stage_start_1": {
    "chestId": "mpe_i_1_stage_start_1",
    "currentValue": 0,
    "maxValue": 2,
    "badgeType": "badge_brewery",
    "isFullyLoaded": true,
    "stage": 1,
    "color": "start",
    "position": 0,
    "chestIndex": 1,
    "isMultiColored": false
  },
  "mpe_i_1_stage_start_2": {
    "chestId": "mpe_i_1_stage_start_2",
    "currentValue": 0,
    "maxValue": 2,
    "badgeType": "arcane_residue",
    "isFullyLoaded": true,
    "stage": 1,
    "color": "start",
    "position": 0,
    "chestIndex": 2,
    "isMultiColored": false
  },
  "mpe_i_1_orange_2_1": {
    "chestId": "mpe_i_1_orange_2_1",
    "currentValue": 0,
    "maxValue": 2,
    "badgeType": "druid_staff",
    "isFullyLoaded": true,
    "stage": 1,
    "color": "orange",
    "position": 2,
    "chestIndex": 1,
    "isMultiColored": false
  },
  "mpe_i_1_orange_2_2": {
    "chestId": "mpe_i_1_orange_2_2",
    "currentValue": 0,
    "maxValue": 1,
    "badgeType": "badge_unit",
    "isFullyLoaded": true,
    "stage": 1,
    "color": "orange",
    "position": 2,
    "chestIndex": 2,
    "isMultiColored": false
  },
  "mpe_i_1_orange_2_3": {
    "chestId": "mpe_i_1_orange_2_3",
    "currentValue": 0,
    "maxValue": 3,
    "badgeType": "witch_hat",
    "isFullyLoaded": true,
    "stage": 1,
    "color": "orange",
    "position": 2,
    "chestIndex": 3,
    "isMultiColored": false
  },
  "mpe_i_1_blue_2_1": {
    "chestId": "mpe_i_1_blue_2_1",
    "currentValue": 0,
    "maxValue": 7,
    "badgeType": "elegant_statue",
    "isFullyLoaded": true,
    "stage": 1,
    "color": "blue",
    "position": 2,
    "chestIndex": 1,
    "isMultiColored": false
  },
  "mpe_i_1_blue_2_2": {
    "chestId": "mpe_i_1_blue_2_2",
    "currentValue": 0,
    "maxValue": 3,
    "badgeType": "badge_brewery",
    "isFullyLoaded": true,
    "stage": 1,
    "color": "blue",
    "position": 2,
    "chestIndex": 2,
    "isMultiColored": false
  },
  "mpe_i_1_blue_2_3": {
    "chestId": "mpe_i_1_blue_2_3",
    "currentValue": 0,
    "maxValue": 6,
    "badgeType": "recycled_potion",
    "isFullyLoaded": true,
    "stage": 1,
    "color": "blue",
    "position": 2,
    "chestIndex": 3,
    "isMultiColored": false
  },
  "mpe_i_1_green_2_1": {
    "chestId": "mpe_i_1_green_2_1",
    "currentValue": 0,
    "maxValue": 3,
    "badgeType": "druid_staff",
    "isFullyLoaded": true,
    "stage": 1,
    "color": "green",
    "position": 2,
    "chestIndex": 1,
    "isMultiColored": false
  },
  "mpe_i_1_green_2_2": {
    "chestId": "mpe_i_1_green_2_2",
    "currentValue": 0,
    "maxValue": 4,
    "badgeType": "witch_hat",
    "isFullyLoaded": true,
    "stage": 1,
    "color": "green",
    "position": 2,
    "chestIndex": 2,
    "isMultiColored": false
  },
  "mpe_i_1_green_2_3": {
    "chestId": "mpe_i_1_green_2_3",
    "currentValue": 0,
    "maxValue": 4,
    "badgeType": "badge_carpenters",
    "isFullyLoaded": true,
    "stage": 1,
    "color": "green",
    "position": 2,
    "chestIndex": 3,
    "isMultiColored": false
  },
  "mpe_i_1_orange_3_1": {
    "chestId": "mpe_i_1_orange_3_1",
    "currentValue": 0,
    "maxValue": 1,
    "badgeType": "elegant_statue",
    "isFullyLoaded": true,
    "stage": 1,
    "color": "orange",
    "position": 3,
    "chestIndex": 1,
    "isMultiColored": true
  },
  "mpe_i_1_orange_3_2": {
    "chestId": "mpe_i_1_orange_3_2",
    "currentValue": 0,
    "maxValue": 1,
    "badgeType": "golden_bracelet",
    "isFullyLoaded": true,
    "stage": 1,
    "color": "orange",
    "position": 3,
    "chestIndex": 2,
    "isMultiColored": true
  },
  "mpe_i_1_orange_3_3": {
    "chestId": "mpe_i_1_orange_3_3",
    "currentValue": 0,
    "maxValue": 7,
    "badgeType": "money_sack",
    "isFullyLoaded": true,
    "stage": 1,
    "color": "orange",
    "position": 3,
    "chestIndex": 3,
    "isMultiColored": true
  },
  "mpe_i_1_blue_3_1": {
    "chestId": "mpe_i_1_blue_3_1",
    "currentValue": 0,
    "maxValue": 4,
    "badgeType": "badge_blacksmith",
    "isFullyLoaded": true,
    "stage": 1,
    "color": "blue",
    "position": 3,
    "chestIndex": 1,
    "isMultiColored": true
  },
  "mpe_i_1_blue_3_2": {
    "chestId": "mpe_i_1_blue_3_2",
    "currentValue": 0,
    "maxValue": 5,
    "badgeType": "badge_unit",
    "isFullyLoaded": true,
    "stage": 1,
    "color": "blue",
    "position": 3,
    "chestIndex": 2,
    "isMultiColored": true
  },
  "mpe_i_1_blue_3_3": {
    "chestId": "mpe_i_1_blue_3_3",
    "currentValue": 0,
    "maxValue": 2,
    "badgeType": "badge_carpenters",
    "isFullyLoaded": true,
    "stage": 1,
    "color": "blue",
    "position": 3,
    "chestIndex": 3,
    "isMultiColored": true
  },
  "mpe_i_1_green_3_1": {
    "chestId": "mpe_i_1_green_3_1",
    "currentValue": 0,
    "maxValue": 6,
    "badgeType": "badge_wonderhelper",
    "isFullyLoaded": true,
    "stage": 1,
    "color": "green",
    "position": 3,
    "chestIndex": 1,
    "isMultiColored": true
  },
  "mpe_i_1_green_3_2": {
    "chestId": "mpe_i_1_green_3_2",
    "currentValue": 0,
    "maxValue": 2,
    "badgeType": "diamond_necklace",
    "isFullyLoaded": true,
    "stage": 1,
    "color": "green",
    "position": 3,
    "chestIndex": 2,
    "isMultiColored": true
  },
  "mpe_i_1_green_3_3": {
    "chestId": "mpe_i_1_green_3_3",
    "currentValue": 0,
    "maxValue": 3,
    "badgeType": "badge_blacksmith",
    "isFullyLoaded": true,
    "stage": 1,
    "color": "green",
    "position": 3,
    "chestIndex": 3,
    "isMultiColored": true
  },
  "mpe_i_1_orange_4_1": {
    "chestId": "mpe_i_1_orange_4_1",
    "currentValue": 0,
    "maxValue": 2,
    "badgeType": "badge_blacksmith",
    "isFullyLoaded": true,
    "stage": 1,
    "color": "orange",
    "position": 4,
    "chestIndex": 1,
    "isMultiColored": false
  },
  "mpe_i_1_orange_4_2": {
    "chestId": "mpe_i_1_orange_4_2",
    "currentValue": 0,
    "maxValue": 8,
    "badgeType": "arcane_residue",
    "isFullyLoaded": true,
    "stage": 1,
    "color": "orange",
    "position": 4,
    "chestIndex": 2,
    "isMultiColored": false
  },
  "mpe_i_1_orange_4_3": {
    "chestId": "mpe_i_1_orange_4_3",
    "currentValue": 0,
    "maxValue": 1,
    "badgeType": "badge_farmers",
    "isFullyLoaded": true,
    "stage": 1,
    "color": "orange",
    "position": 4,
    "chestIndex": 3,
    "isMultiColored": false
  },
  "mpe_i_1_blue_4_1": {
    "chestId": "mpe_i_1_blue_4_1",
    "currentValue": 0,
    "maxValue": 5,
    "badgeType": "money_sack",
    "isFullyLoaded": true,
    "stage": 1,
    "color": "blue",
    "position": 4,
    "chestIndex": 1,
    "isMultiColored": false
  },
  "mpe_i_1_blue_4_2": {
    "chestId": "mpe_i_1_blue_4_2",
    "currentValue": 0,
    "maxValue": 3,
    "badgeType": "arcane_residue",
    "isFullyLoaded": true,
    "stage": 1,
    "color": "blue",
    "position": 4,
    "chestIndex": 2,
    "isMultiColored": false
  },
  "mpe_i_1_blue_4_3": {
    "chestId": "mpe_i_1_blue_4_3",
    "currentValue": 0,
    "maxValue": 2,
    "badgeType": "witch_hat",
    "isFullyLoaded": true,
    "stage": 1,
    "color": "blue",
    "position": 4,
    "chestIndex": 3,
    "isMultiColored": false
  },
  "mpe_i_1_green_4_1": {
    "chestId": "mpe_i_1_green_4_1",
    "currentValue": 0,
    "maxValue": 5,
    "badgeType": "badge_unit",
    "isFullyLoaded": true,
    "stage": 1,
    "color": "green",
    "position": 4,
    "chestIndex": 1,
    "isMultiColored": false
  },
  "mpe_i_1_green_4_2": {
    "chestId": "mpe_i_1_green_4_2",
    "currentValue": 0,
    "maxValue": 2,
    "badgeType": "ghost_in_a_bottle",
    "isFullyLoaded": true,
    "stage": 1,
    "color": "green",
    "position": 4,
    "chestIndex": 2,
    "isMultiColored": false
  },
  "mpe_i_1_green_4_3": {
    "chestId": "mpe_i_1_green_4_3",
    "currentValue": 0,
    "maxValue": 3,
    "badgeType": "druid_staff",
    "isFullyLoaded": true,
    "stage": 1,
    "color": "green",
    "position": 4,
    "chestIndex": 3,
    "isMultiColored": false
  },
  "mpe_i_1_orange_5_1": {
    "chestId": "mpe_i_1_orange_5_1",
    "currentValue": 0,
    "maxValue": 2,
    "badgeType": "badge_carpenters",
    "isFullyLoaded": true,
    "stage": 1,
    "color": "orange",
    "position": 5,
    "chestIndex": 1,
    "isMultiColored": false
  },
  "mpe_i_1_orange_5_2": {
    "chestId": "mpe_i_1_orange_5_2",
    "currentValue": 0,
    "maxValue": 1,
    "badgeType": "badge_unit",
    "isFullyLoaded": true,
    "stage": 1,
    "color": "orange",
    "position": 5,
    "chestIndex": 2,
    "isMultiColored": false
  },
  "mpe_i_1_orange_5_3": {
    "chestId": "mpe_i_1_orange_5_3",
    "currentValue": 0,
    "maxValue": 8,
    "badgeType": "badge_wonderhelper",
    "isFullyLoaded": true,
    "stage": 1,
    "color": "orange",
    "position": 5,
    "chestIndex": 3,
    "isMultiColored": false
  },
  "mpe_i_1_blue_5_1": {
    "chestId": "mpe_i_1_blue_5_1",
    "currentValue": 0,
    "maxValue": 5,
    "badgeType": "badge_farmers",
    "isFullyLoaded": true,
    "stage": 1,
    "color": "blue",
    "position": 5,
    "chestIndex": 1,
    "isMultiColored": false
  },
  "mpe_i_1_blue_5_2": {
    "chestId": "mpe_i_1_blue_5_2",
    "currentValue": 0,
    "maxValue": 3,
    "badgeType": "diamond_necklace",
    "isFullyLoaded": true,
    "stage": 1,
    "color": "blue",
    "position": 5,
    "chestIndex": 2,
    "isMultiColored": false
  },
  "mpe_i_1_blue_5_3": {
    "chestId": "mpe_i_1_blue_5_3",
    "currentValue": 0,
    "maxValue": 2,
    "badgeType": "badge_carpenters",
    "isFullyLoaded": true,
    "stage": 1,
    "color": "blue",
    "position": 5,
    "chestIndex": 3,
    "isMultiColored": false
  },
  "mpe_i_1_green_5_1": {
    "chestId": "mpe_i_1_green_5_1",
    "currentValue": 0,
    "maxValue": 2,
    "badgeType": "enchanted_tiara",
    "isFullyLoaded": true,
    "stage": 1,
    "color": "green",
    "position": 5,
    "chestIndex": 1,
    "isMultiColored": false
  },
  "mpe_i_1_green_5_2": {
    "chestId": "mpe_i_1_green_5_2",
    "currentValue": 0,
    "maxValue": 2,
    "badgeType": "golden_bracelet",
    "isFullyLoaded": true,
    "stage": 1,
    "color": "green",
    "position": 5,
    "chestIndex": 2,
    "isMultiColored": false
  },
  "mpe_i_1_green_5_3": {
    "chestId": "mpe_i_1_green_5_3",
    "currentValue": 0,
    "maxValue": 3,
    "badgeType": "recycled_potion",
    "isFullyLoaded": true,
    "stage": 1,
    "color": "green",
    "position": 5,
    "chestIndex": 3,
    "isMultiColored": false
  },
  "mpe_i_1_orange_6_1": {
    "chestId": "mpe_i_1_orange_6_1",
    "currentValue": 0,
    "maxValue": 7,
    "badgeType": "badge_brewery",
    "isFullyLoaded": true,
    "stage": 1,
    "color": "orange",
    "position": 6,
    "chestIndex": 1,
    "isMultiColored": true
  },
  "mpe_i_1_orange_6_2": {
    "chestId": "mpe_i_1_orange_6_2",
    "currentValue": 0,
    "maxValue": 1,
    "badgeType": "elegant_statue",
    "isFullyLoaded": true,
    "stage": 1,
    "color": "orange",
    "position": 6,
    "chestIndex": 2,
    "isMultiColored": true
  },
  "mpe_i_1_orange_6_3": {
    "chestId": "mpe_i_1_orange_6_3",
    "currentValue": 0,
    "maxValue": 8,
    "badgeType": "ghost_in_a_bottle",
    "isFullyLoaded": true,
    "stage": 1,
    "color": "orange",
    "position": 6,
    "chestIndex": 3,
    "isMultiColored": true
  },
  "mpe_i_1_blue_6_1": {
    "chestId": "mpe_i_1_blue_6_1",
    "currentValue": 0,
    "maxValue": 5,
    "badgeType": "money_sack",
    "isFullyLoaded": true,
    "stage": 1,
    "color": "blue",
    "position": 6,
    "chestIndex": 1,
    "isMultiColored": true
  },
  "mpe_i_1_blue_6_2": {
    "chestId": "mpe_i_1_blue_6_2",
    "currentValue": 0,
    "maxValue": 2,
    "badgeType": "enchanted_tiara",
    "isFullyLoaded": true,
    "stage": 1,
    "color": "blue",
    "position": 6,
    "chestIndex": 2,
    "isMultiColored": true
  },
  "mpe_i_1_blue_6_3": {
    "chestId": "mpe_i_1_blue_6_3",
    "currentValue": 0,
    "maxValue": 7,
    "badgeType": "golden_bracelet",
    "isFullyLoaded": true,
    "stage": 1,
    "color": "blue",
    "position": 6,
    "chestIndex": 3,
    "isMultiColored": true
  },
  "mpe_i_1_green_6_1": {
    "chestId": "mpe_i_1_green_6_1",
    "currentValue": 0,
    "maxValue": 2,
    "badgeType": "diamond_necklace",
    "isFullyLoaded": true,
    "stage": 1,
    "color": "green",
    "position": 6,
    "chestIndex": 1,
    "isMultiColored": true
  },
  "mpe_i_1_green_6_2": {
    "chestId": "mpe_i_1_green_6_2",
    "currentValue": 0,
    "maxValue": 3,
    "badgeType": "badge_farmers",
    "isFullyLoaded": true,
    "stage": 1,
    "color": "green",
    "position": 6,
    "chestIndex": 2,
    "isMultiColored": true
  },
  "mpe_i_1_green_6_3": {
    "chestId": "mpe_i_1_green_6_3",
    "currentValue": 0,
    "maxValue": 3,
    "badgeType": "arcane_residue",
    "isFullyLoaded": true,
    "stage": 1,
    "color": "green",
    "position": 6,
    "chestIndex": 3,
    "isMultiColored": true
  },
  "mpe_i_1_orange_7_1": {
    "chestId": "mpe_i_1_orange_7_1",
    "currentValue": 0,
    "maxValue": 1,
    "badgeType": "golden_bracelet",
    "isFullyLoaded": true,
    "stage": 1,
    "color": "orange",
    "position": 7,
    "chestIndex": 1,
    "isMultiColored": false
  },
  "mpe_i_1_orange_7_2": {
    "chestId": "mpe_i_1_orange_7_2",
    "currentValue": 0,
    "maxValue": 2,
    "badgeType": "diamond_necklace",
    "isFullyLoaded": true,
    "stage": 1,
    "color": "orange",
    "position": 7,
    "chestIndex": 2,
    "isMultiColored": false
  },
  "mpe_i_1_orange_7_3": {
    "chestId": "mpe_i_1_orange_7_3",
    "currentValue": 0,
    "maxValue": 1,
    "badgeType": "badge_farmers",
    "isFullyLoaded": true,
    "stage": 1,
    "color": "orange",
    "position": 7,
    "chestIndex": 3,
    "isMultiColored": false
  },
  "mpe_i_1_blue_7_1": {
    "chestId": "mpe_i_1_blue_7_1",
    "currentValue": 0,
    "maxValue": 3,
    "badgeType": "badge_brewery",
    "isFullyLoaded": true,
    "stage": 1,
    "color": "blue",
    "position": 7,
    "chestIndex": 1,
    "isMultiColored": false
  },
  "mpe_i_1_blue_7_2": {
    "chestId": "mpe_i_1_blue_7_2",
    "currentValue": 0,
    "maxValue": 4,
    "badgeType": "badge_blacksmith",
    "isFullyLoaded": true,
    "stage": 1,
    "color": "blue",
    "position": 7,
    "chestIndex": 2,
    "isMultiColored": false
  },
  "mpe_i_1_blue_7_3": {
    "chestId": "mpe_i_1_blue_7_3",
    "currentValue": 0,
    "maxValue": 5,
    "badgeType": "badge_unit",
    "isFullyLoaded": true,
    "stage": 1,
    "color": "blue",
    "position": 7,
    "chestIndex": 3,
    "isMultiColored": false
  },
  "mpe_i_1_green_7_1": {
    "chestId": "mpe_i_1_green_7_1",
    "currentValue": 0,
    "maxValue": 3,
    "badgeType": "badge_blacksmith",
    "isFullyLoaded": true,
    "stage": 1,
    "color": "green",
    "position": 7,
    "chestIndex": 1,
    "isMultiColored": false
  },
  "mpe_i_1_green_7_2": {
    "chestId": "mpe_i_1_green_7_2",
    "currentValue": 0,
    "maxValue": 2,
    "badgeType": "enchanted_tiara",
    "isFullyLoaded": true,
    "stage": 1,
    "color": "green",
    "position": 7,
    "chestIndex": 2,
    "isMultiColored": false
  },
  "mpe_i_1_green_7_3": {
    "chestId": "mpe_i_1_green_7_3",
    "currentValue": 0,
    "maxValue": 3,
    "badgeType": "recycled_potion",
    "isFullyLoaded": true,
    "stage": 1,
    "color": "green",
    "position": 7,
    "chestIndex": 3,
    "isMultiColored": false
  },
  "mpe_i_1_orange_8_1": {
    "chestId": "mpe_i_1_orange_8_1",
    "currentValue": 0,
    "maxValue": 5,
    "badgeType": "enchanted_tiara",
    "isFullyLoaded": true,
    "stage": 1,
    "color": "orange",
    "position": 8,
    "chestIndex": 1,
    "isMultiColored": false
  },
  "mpe_i_1_orange_8_2": {
    "chestId": "mpe_i_1_orange_8_2",
    "currentValue": 0,
    "maxValue": 2,
    "badgeType": "druid_staff",
    "isFullyLoaded": true,
    "stage": 1,
    "color": "orange",
    "position": 8,
    "chestIndex": 2,
    "isMultiColored": false
  },
  "mpe_i_1_orange_8_3": {
    "chestId": "mpe_i_1_orange_8_3",
    "currentValue": 0,
    "maxValue": 2,
    "badgeType": "badge_carpenters",
    "isFullyLoaded": true,
    "stage": 1,
    "color": "orange",
    "position": 8,
    "chestIndex": 3,
    "isMultiColored": false
  },
  "mpe_i_1_blue_8_1": {
    "chestId": "mpe_i_1_blue_8_1",
    "currentValue": 0,
    "maxValue": 2,
    "badgeType": "witch_hat",
    "isFullyLoaded": true,
    "stage": 1,
    "color": "blue",
    "position": 8,
    "chestIndex": 1,
    "isMultiColored": false
  },
  "mpe_i_1_blue_8_2": {
    "chestId": "mpe_i_1_blue_8_2",
    "currentValue": 0,
    "maxValue": 8,
    "badgeType": "druid_staff",
    "isFullyLoaded": true,
    "stage": 1,
    "color": "blue",
    "position": 8,
    "chestIndex": 2,
    "isMultiColored": false
  },
  "mpe_i_1_blue_8_3": {
    "chestId": "mpe_i_1_blue_8_3",
    "currentValue": 0,
    "maxValue": 3,
    "badgeType": "ghost_in_a_bottle",
    "isFullyLoaded": true,
    "stage": 1,
    "color": "blue",
    "position": 8,
    "chestIndex": 3,
    "isMultiColored": false
  },
  "mpe_i_1_green_8_1": {
    "chestId": "mpe_i_1_green_8_1",
    "currentValue": 0,
    "maxValue": 2,
    "badgeType": "golden_bracelet",
    "isFullyLoaded": true,
    "stage": 1,
    "color": "green",
    "position": 8,
    "chestIndex": 1,
    "isMultiColored": false
  },
  "mpe_i_1_green_8_2": {
    "chestId": "mpe_i_1_green_8_2",
    "currentValue": 0,
    "maxValue": 2,
    "badgeType": "ghost_in_a_bottle",
    "isFullyLoaded": true,
    "stage": 1,
    "color": "green",
    "position": 8,
    "chestIndex": 2,
    "isMultiColored": false
  },
  "mpe_i_1_green_8_3": {
    "chestId": "mpe_i_1_green_8_3",
    "currentValue": 0,
    "maxValue": 9,
    "badgeType": "money_sack",
    "isFullyLoaded": true,
    "stage": 1,
    "color": "green",
    "position": 8,
    "chestIndex": 3,
    "isMultiColored": false
  },
  "mpe_i_1_orange_9_1": {
    "chestId": "mpe_i_1_orange_9_1",
    "currentValue": 0,
    "maxValue": 7,
    "badgeType": "recycled_potion",
    "isFullyLoaded": true,
    "stage": 1,
    "color": "orange",
    "position": 9,
    "chestIndex": 1,
    "isMultiColored": false
  },
  "mpe_i_1_orange_9_2": {
    "chestId": "mpe_i_1_orange_9_2",
    "currentValue": 0,
    "maxValue": 2,
    "badgeType": "badge_blacksmith",
    "isFullyLoaded": true,
    "stage": 1,
    "color": "orange",
    "position": 9,
    "chestIndex": 2,
    "isMultiColored": false
  },
  "mpe_i_1_orange_9_3": {
    "chestId": "mpe_i_1_orange_9_3",
    "currentValue": 0,
    "maxValue": 2,
    "badgeType": "diamond_necklace",
    "isFullyLoaded": true,
    "stage": 1,
    "color": "orange",
    "position": 9,
    "chestIndex": 3,
    "isMultiColored": false
  },
  "mpe_i_1_blue_9_1": {
    "chestId": "mpe_i_1_blue_9_1",
    "currentValue": 0,
    "maxValue": 5,
    "badgeType": "badge_wonderhelper",
    "isFullyLoaded": true,
    "stage": 1,
    "color": "blue",
    "position": 9,
    "chestIndex": 1,
    "isMultiColored": false
  },
  "mpe_i_1_blue_9_2": {
    "chestId": "mpe_i_1_blue_9_2",
    "currentValue": 0,
    "maxValue": 3,
    "badgeType": "diamond_necklace",
    "isFullyLoaded": true,
    "stage": 1,
    "color": "blue",
    "position": 9,
    "chestIndex": 2,
    "isMultiColored": false
  },
  "mpe_i_1_blue_9_3": {
    "chestId": "mpe_i_1_blue_9_3",
    "currentValue": 0,
    "maxValue": 3,
    "badgeType": "badge_brewery",
    "isFullyLoaded": true,
    "stage": 1,
    "color": "blue",
    "position": 9,
    "chestIndex": 3,
    "isMultiColored": false
  },
  "mpe_i_1_green_9_1": {
    "chestId": "mpe_i_1_green_9_1",
    "currentValue": 0,
    "maxValue": 3,
    "badgeType": "elegant_statue",
    "isFullyLoaded": true,
    "stage": 1,
    "color": "green",
    "position": 9,
    "chestIndex": 1,
    "isMultiColored": false
  },
  "mpe_i_1_green_9_2": {
    "chestId": "mpe_i_1_green_9_2",
    "currentValue": 0,
    "maxValue": 3,
    "badgeType": "arcane_residue",
    "isFullyLoaded": true,
    "stage": 1,
    "color": "green",
    "position": 9,
    "chestIndex": 2,
    "isMultiColored": false
  },
  "mpe_i_1_green_9_3": {
    "chestId": "mpe_i_1_green_9_3",
    "currentValue": 0,
    "maxValue": 8,
    "badgeType": "badge_brewery",
    "isFullyLoaded": true,
    "stage": 1,
    "color": "green",
    "position": 9,
    "chestIndex": 3,
    "isMultiColored": false
  },
  "mpe_i_2_stage_start_1": {
    "chestId": "mpe_i_2_stage_start_1",
    "currentValue": 0,
    "maxValue": 2,
    "badgeType": "diamond_necklace",
    "isFullyLoaded": true,
    "stage": 2,
    "color": "start",
    "position": 0,
    "chestIndex": 1,
    "isMultiColored": false
  },
  "mpe_i_2_stage_start_2": {
    "chestId": "mpe_i_2_stage_start_2",
    "currentValue": 0,
    "maxValue": 2,
    "badgeType": "golden_bracelet",
    "isFullyLoaded": true,
    "stage": 2,
    "color": "start",
    "position": 0,
    "chestIndex": 2,
    "isMultiColored": false
  },
  "mpe_i_2_orange_2_1": {
    "chestId": "mpe_i_2_orange_2_1",
    "currentValue": 0,
    "maxValue": 8,
    "badgeType": "badge_unit",
    "isFullyLoaded": true,
    "stage": 2,
    "color": "orange",
    "position": 2,
    "chestIndex": 1,
    "isMultiColored": false
  },
  "mpe_i_2_orange_2_2": {
    "chestId": "mpe_i_2_orange_2_2",
    "currentValue": 0,
    "maxValue": 16,
    "badgeType": "badge_wonderhelper",
    "isFullyLoaded": true,
    "stage": 2,
    "color": "orange",
    "position": 2,
    "chestIndex": 2,
    "isMultiColored": false
  },
  "mpe_i_2_orange_2_3": {
    "chestId": "mpe_i_2_orange_2_3",
    "currentValue": 0,
    "maxValue": 16,
    "badgeType": "arcane_residue",
    "isFullyLoaded": true,
    "stage": 2,
    "color": "orange",
    "position": 2,
    "chestIndex": 3,
    "isMultiColored": false
  },
  "mpe_i_2_blue_2_1": {
    "chestId": "mpe_i_2_blue_2_1",
    "currentValue": 0,
    "maxValue": 10,
    "badgeType": "ghost_in_a_bottle",
    "isFullyLoaded": true,
    "stage": 2,
    "color": "blue",
    "position": 2,
    "chestIndex": 1,
    "isMultiColored": false
  },
  "mpe_i_2_blue_2_2": {
    "chestId": "mpe_i_2_blue_2_2",
    "currentValue": 0,
    "maxValue": 13,
    "badgeType": "elegant_statue",
    "isFullyLoaded": true,
    "stage": 2,
    "color": "blue",
    "position": 2,
    "chestIndex": 2,
    "isMultiColored": false
  },
  "mpe_i_2_blue_2_3": {
    "chestId": "mpe_i_2_blue_2_3",
    "currentValue": 0,
    "maxValue": 15,
    "badgeType": "badge_blacksmith",
    "isFullyLoaded": true,
    "stage": 2,
    "color": "blue",
    "position": 2,
    "chestIndex": 3,
    "isMultiColored": false
  },
  "mpe_i_2_green_2_1": {
    "chestId": "mpe_i_2_green_2_1",
    "currentValue": 0,
    "maxValue": 7,
    "badgeType": "witch_hat",
    "isFullyLoaded": true,
    "stage": 2,
    "color": "green",
    "position": 2,
    "chestIndex": 1,
    "isMultiColored": false
  },
  "mpe_i_2_green_2_2": {
    "chestId": "mpe_i_2_green_2_2",
    "currentValue": 0,
    "maxValue": 4,
    "badgeType": "golden_bracelet",
    "isFullyLoaded": true,
    "stage": 2,
    "color": "green",
    "position": 2,
    "chestIndex": 2,
    "isMultiColored": false
  },
  "mpe_i_2_green_2_3": {
    "chestId": "mpe_i_2_green_2_3",
    "currentValue": 0,
    "maxValue": 25,
    "badgeType": "badge_wonderhelper",
    "isFullyLoaded": true,
    "stage": 2,
    "color": "green",
    "position": 2,
    "chestIndex": 3,
    "isMultiColored": false
  },
  "mpe_i_2_orange_3_1": {
    "chestId": "mpe_i_2_orange_3_1",
    "currentValue": 0,
    "maxValue": 12,
    "badgeType": "diamond_necklace",
    "isFullyLoaded": true,
    "stage": 2,
    "color": "orange",
    "position": 3,
    "chestIndex": 1,
    "isMultiColored": true
  },
  "mpe_i_2_orange_3_2": {
    "chestId": "mpe_i_2_orange_3_2",
    "currentValue": 0,
    "maxValue": 25,
    "badgeType": "recycled_potion",
    "isFullyLoaded": true,
    "stage": 2,
    "color": "orange",
    "position": 3,
    "chestIndex": 2,
    "isMultiColored": true
  },
  "mpe_i_2_orange_3_3": {
    "chestId": "mpe_i_2_orange_3_3",
    "currentValue": 0,
    "maxValue": 13,
    "badgeType": "witch_hat",
    "isFullyLoaded": true,
    "stage": 2,
    "color": "orange",
    "position": 3,
    "chestIndex": 3,
    "isMultiColored": true
  },
  "mpe_i_2_blue_3_1": {
    "chestId": "mpe_i_2_blue_3_1",
    "currentValue": 0,
    "maxValue": 8,
    "badgeType": "witch_hat",
    "isFullyLoaded": true,
    "stage": 2,
    "color": "blue",
    "position": 3,
    "chestIndex": 1,
    "isMultiColored": true
  },
  "mpe_i_2_blue_3_2": {
    "chestId": "mpe_i_2_blue_3_2",
    "currentValue": 0,
    "maxValue": 13,
    "badgeType": "diamond_necklace",
    "isFullyLoaded": true,
    "stage": 2,
    "color": "blue",
    "position": 3,
    "chestIndex": 2,
    "isMultiColored": true
  },
  "mpe_i_2_blue_3_3": {
    "chestId": "mpe_i_2_blue_3_3",
    "currentValue": 0,
    "maxValue": 39,
    "badgeType": "badge_unit",
    "isFullyLoaded": true,
    "stage": 2,
    "color": "blue",
    "position": 3,
    "chestIndex": 3,
    "isMultiColored": true
  },
  "mpe_i_2_green_3_1": {
    "chestId": "mpe_i_2_green_3_1",
    "currentValue": 0,
    "maxValue": 18,
    "badgeType": "ghost_in_a_bottle",
    "isFullyLoaded": true,
    "stage": 2,
    "color": "green",
    "position": 3,
    "chestIndex": 1,
    "isMultiColored": true
  },
  "mpe_i_2_green_3_2": {
    "chestId": "mpe_i_2_green_3_2",
    "currentValue": 0,
    "maxValue": 25,
    "badgeType": "recycled_potion",
    "isFullyLoaded": true,
    "stage": 2,
    "color": "green",
    "position": 3,
    "chestIndex": 2,
    "isMultiColored": true
  },
  "mpe_i_2_green_3_3": {
    "chestId": "mpe_i_2_green_3_3",
    "currentValue": 0,
    "maxValue": 33,
    "badgeType": "money_sack",
    "isFullyLoaded": true,
    "stage": 2,
    "color": "green",
    "position": 3,
    "chestIndex": 3,
    "isMultiColored": true
  },
  "mpe_i_2_orange_4_1": {
    "chestId": "mpe_i_2_orange_4_1",
    "currentValue": 0,
    "maxValue": 7,
    "badgeType": "badge_carpenters",
    "isFullyLoaded": true,
    "stage": 2,
    "color": "orange",
    "position": 4,
    "chestIndex": 1,
    "isMultiColored": false
  },
  "mpe_i_2_orange_4_2": {
    "chestId": "mpe_i_2_orange_4_2",
    "currentValue": 0,
    "maxValue": 14,
    "badgeType": "badge_blacksmith",
    "isFullyLoaded": true,
    "stage": 2,
    "color": "orange",
    "position": 4,
    "chestIndex": 2,
    "isMultiColored": false
  },
  "mpe_i_2_orange_4_3": {
    "chestId": "mpe_i_2_orange_4_3",
    "currentValue": 0,
    "maxValue": 16,
    "badgeType": "badge_wonderhelper",
    "isFullyLoaded": true,
    "stage": 2,
    "color": "orange",
    "position": 4,
    "chestIndex": 3,
    "isMultiColored": false
  },
  "mpe_i_2_blue_4_1": {
    "chestId": "mpe_i_2_blue_4_1",
    "currentValue": 0,
    "maxValue": 4,
    "badgeType": "arcane_residue",
    "isFullyLoaded": true,
    "stage": 2,
    "color": "blue",
    "position": 4,
    "chestIndex": 1,
    "isMultiColored": false
  },
  "mpe_i_2_blue_4_2": {
    "chestId": "mpe_i_2_blue_4_2",
    "currentValue": 0,
    "maxValue": 17,
    "badgeType": "money_sack",
    "isFullyLoaded": true,
    "stage": 2,
    "color": "blue",
    "position": 4,
    "chestIndex": 2,
    "isMultiColored": false
  },
  "mpe_i_2_blue_4_3": {
    "chestId": "mpe_i_2_blue_4_3",
    "currentValue": 0,
    "maxValue": 6,
    "badgeType": "enchanted_tiara",
    "isFullyLoaded": true,
    "stage": 2,
    "color": "blue",
    "position": 4,
    "chestIndex": 3,
    "isMultiColored": false
  },
  "mpe_i_2_green_4_1": {
    "chestId": "mpe_i_2_green_4_1",
    "currentValue": 0,
    "maxValue": 4,
    "badgeType": "golden_bracelet",
    "isFullyLoaded": true,
    "stage": 2,
    "color": "green",
    "position": 4,
    "chestIndex": 1,
    "isMultiColored": false
  },
  "mpe_i_2_green_4_2": {
    "chestId": "mpe_i_2_green_4_2",
    "currentValue": 0,
    "maxValue": 21,
    "badgeType": "druid_staff",
    "isFullyLoaded": true,
    "stage": 2,
    "color": "green",
    "position": 4,
    "chestIndex": 2,
    "isMultiColored": false
  },
  "mpe_i_2_green_4_3": {
    "chestId": "mpe_i_2_green_4_3",
    "currentValue": 0,
    "maxValue": 11,
    "badgeType": "badge_blacksmith",
    "isFullyLoaded": true,
    "stage": 2,
    "color": "green",
    "position": 4,
    "chestIndex": 3,
    "isMultiColored": false
  },
  "mpe_i_2_orange_5_1": {
    "chestId": "mpe_i_2_orange_5_1",
    "currentValue": 0,
    "maxValue": 5,
    "badgeType": "golden_bracelet",
    "isFullyLoaded": true,
    "stage": 2,
    "color": "orange",
    "position": 5,
    "chestIndex": 1,
    "isMultiColored": false
  },
  "mpe_i_2_orange_5_2": {
    "chestId": "mpe_i_2_orange_5_2",
    "currentValue": 0,
    "maxValue": 13,
    "badgeType": "badge_brewery",
    "isFullyLoaded": true,
    "stage": 2,
    "color": "orange",
    "position": 5,
    "chestIndex": 2,
    "isMultiColored": false
  },
  "mpe_i_2_orange_5_3": {
    "chestId": "mpe_i_2_orange_5_3",
    "currentValue": 0,
    "maxValue": 16,
    "badgeType": "ghost_in_a_bottle",
    "isFullyLoaded": true,
    "stage": 2,
    "color": "orange",
    "position": 5,
    "chestIndex": 3,
    "isMultiColored": false
  },
  "mpe_i_2_blue_5_1": {
    "chestId": "mpe_i_2_blue_5_1",
    "currentValue": 0,
    "maxValue": 32,
    "badgeType": "badge_brewery",
    "isFullyLoaded": true,
    "stage": 2,
    "color": "blue",
    "position": 5,
    "chestIndex": 1,
    "isMultiColored": false
  },
  "mpe_i_2_blue_5_2": {
    "chestId": "mpe_i_2_blue_5_2",
    "currentValue": 0,
    "maxValue": 15,
    "badgeType": "badge_blacksmith",
    "isFullyLoaded": true,
    "stage": 2,
    "color": "blue",
    "position": 5,
    "chestIndex": 2,
    "isMultiColored": false
  },
  "mpe_i_2_blue_5_3": {
    "chestId": "mpe_i_2_blue_5_3",
    "currentValue": 0,
    "maxValue": 17,
    "badgeType": "badge_wonderhelper",
    "isFullyLoaded": true,
    "stage": 2,
    "color": "blue",
    "position": 5,
    "chestIndex": 3,
    "isMultiColored": false
  },
  "mpe_i_2_green_5_1": {
    "chestId": "mpe_i_2_green_5_1",
    "currentValue": 0,
    "maxValue": 18,
    "badgeType": "badge_unit",
    "isFullyLoaded": true,
    "stage": 2,
    "color": "green",
    "position": 5,
    "chestIndex": 1,
    "isMultiColored": false
  },
  "mpe_i_2_green_5_2": {
    "chestId": "mpe_i_2_green_5_2",
    "currentValue": 0,
    "maxValue": 6,
    "badgeType": "enchanted_tiara",
    "isFullyLoaded": true,
    "stage": 2,
    "color": "green",
    "position": 5,
    "chestIndex": 2,
    "isMultiColored": false
  },
  "mpe_i_2_green_5_3": {
    "chestId": "mpe_i_2_green_5_3",
    "currentValue": 0,
    "maxValue": 6,
    "badgeType": "elegant_statue",
    "isFullyLoaded": true,
    "stage": 2,
    "color": "green",
    "position": 5,
    "chestIndex": 3,
    "isMultiColored": false
  },
  "mpe_i_2_orange_6_1": {
    "chestId": "mpe_i_2_orange_6_1",
    "currentValue": 0,
    "maxValue": 14,
    "badgeType": "money_sack",
    "isFullyLoaded": true,
    "stage": 2,
    "color": "orange",
    "position": 6,
    "chestIndex": 1,
    "isMultiColored": true
  },
  "mpe_i_2_orange_6_2": {
    "chestId": "mpe_i_2_orange_6_2",
    "currentValue": 0,
    "maxValue": 10,
    "badgeType": "enchanted_tiara",
    "isFullyLoaded": true,
    "stage": 2,
    "color": "orange",
    "position": 6,
    "chestIndex": 2,
    "isMultiColored": true
  },
  "mpe_i_2_orange_6_3": {
    "chestId": "mpe_i_2_orange_6_3",
    "currentValue": 0,
    "maxValue": 8,
    "badgeType": "badge_farmers",
    "isFullyLoaded": true,
    "stage": 2,
    "color": "orange",
    "position": 6,
    "chestIndex": 3,
    "isMultiColored": true
  },
  "mpe_i_2_blue_6_1": {
    "chestId": "mpe_i_2_blue_6_1",
    "currentValue": 0,
    "maxValue": 8,
    "badgeType": "witch_hat",
    "isFullyLoaded": true,
    "stage": 2,
    "color": "blue",
    "position": 6,
    "chestIndex": 1,
    "isMultiColored": true
  },
  "mpe_i_2_blue_6_2": {
    "chestId": "mpe_i_2_blue_6_2",
    "currentValue": 0,
    "maxValue": 9,
    "badgeType": "badge_farmers",
    "isFullyLoaded": true,
    "stage": 2,
    "color": "blue",
    "position": 6,
    "chestIndex": 2,
    "isMultiColored": true
  },
  "mpe_i_2_blue_6_3": {
    "chestId": "mpe_i_2_blue_6_3",
    "currentValue": 0,
    "maxValue": 12,
    "badgeType": "badge_carpenters",
    "isFullyLoaded": true,
    "stage": 2,
    "color": "blue",
    "position": 6,
    "chestIndex": 3,
    "isMultiColored": true
  },
  "mpe_i_2_green_6_1": {
    "chestId": "mpe_i_2_green_6_1",
    "currentValue": 0,
    "maxValue": 31,
    "badgeType": "badge_brewery",
    "isFullyLoaded": true,
    "stage": 2,
    "color": "green",
    "position": 6,
    "chestIndex": 1,
    "isMultiColored": true
  },
  "mpe_i_2_green_6_2": {
    "chestId": "mpe_i_2_green_6_2",
    "currentValue": 0,
    "maxValue": 6,
    "badgeType": "badge_farmers",
    "isFullyLoaded": true,
    "stage": 2,
    "color": "green",
    "position": 6,
    "chestIndex": 2,
    "isMultiColored": true
  },
  "mpe_i_2_green_6_3": {
    "chestId": "mpe_i_2_green_6_3",
    "currentValue": 0,
    "maxValue": 11,
    "badgeType": "arcane_residue",
    "isFullyLoaded": true,
    "stage": 2,
    "color": "green",
    "position": 6,
    "chestIndex": 3,
    "isMultiColored": true
  },
  "mpe_i_2_orange_7_1": {
    "chestId": "mpe_i_2_orange_7_1",
    "currentValue": 0,
    "maxValue": 13,
    "badgeType": "badge_brewery",
    "isFullyLoaded": true,
    "stage": 2,
    "color": "orange",
    "position": 7,
    "chestIndex": 1,
    "isMultiColored": false
  },
  "mpe_i_2_orange_7_2": {
    "chestId": "mpe_i_2_orange_7_2",
    "currentValue": 0,
    "maxValue": 7,
    "badgeType": "druid_staff",
    "isFullyLoaded": true,
    "stage": 2,
    "color": "orange",
    "position": 7,
    "chestIndex": 2,
    "isMultiColored": false
  },
  "mpe_i_2_orange_7_3": {
    "chestId": "mpe_i_2_orange_7_3",
    "currentValue": 0,
    "maxValue": 5,
    "badgeType": "elegant_statue",
    "isFullyLoaded": true,
    "stage": 2,
    "color": "orange",
    "position": 7,
    "chestIndex": 3,
    "isMultiColored": false
  },
  "mpe_i_2_blue_7_1": {
    "chestId": "mpe_i_2_blue_7_1",
    "currentValue": 0,
    "maxValue": 26,
    "badgeType": "golden_bracelet",
    "isFullyLoaded": true,
    "stage": 2,
    "color": "blue",
    "position": 7,
    "chestIndex": 1,
    "isMultiColored": false
  },
  "mpe_i_2_blue_7_2": {
    "chestId": "mpe_i_2_blue_7_2",
    "currentValue": 0,
    "maxValue": 4,
    "badgeType": "arcane_residue",
    "isFullyLoaded": true,
    "stage": 2,
    "color": "blue",
    "position": 7,
    "chestIndex": 2,
    "isMultiColored": false
  },
  "mpe_i_2_blue_7_3": {
    "chestId": "mpe_i_2_blue_7_3",
    "currentValue": 0,
    "maxValue": 21,
    "badgeType": "recycled_potion",
    "isFullyLoaded": true,
    "stage": 2,
    "color": "blue",
    "position": 7,
    "chestIndex": 3,
    "isMultiColored": false
  },
  "mpe_i_2_green_7_1": {
    "chestId": "mpe_i_2_green_7_1",
    "currentValue": 0,
    "maxValue": 11,
    "badgeType": "badge_blacksmith",
    "isFullyLoaded": true,
    "stage": 2,
    "color": "green",
    "position": 7,
    "chestIndex": 1,
    "isMultiColored": false
  },
  "mpe_i_2_green_7_2": {
    "chestId": "mpe_i_2_green_7_2",
    "currentValue": 0,
    "maxValue": 6,
    "badgeType": "elegant_statue",
    "isFullyLoaded": true,
    "stage": 2,
    "color": "green",
    "position": 7,
    "chestIndex": 2,
    "isMultiColored": false
  },
  "mpe_i_2_green_7_3": {
    "chestId": "mpe_i_2_green_7_3",
    "currentValue": 0,
    "maxValue": 18,
    "badgeType": "diamond_necklace",
    "isFullyLoaded": true,
    "stage": 2,
    "color": "green",
    "position": 7,
    "chestIndex": 3,
    "isMultiColored": false
  },
  "mpe_i_2_orange_8_1": {
    "chestId": "mpe_i_2_orange_8_1",
    "currentValue": 0,
    "maxValue": 16,
    "badgeType": "ghost_in_a_bottle",
    "isFullyLoaded": true,
    "stage": 2,
    "color": "orange",
    "position": 8,
    "chestIndex": 1,
    "isMultiColored": false
  },
  "mpe_i_2_orange_8_2": {
    "chestId": "mpe_i_2_orange_8_2",
    "currentValue": 0,
    "maxValue": 10,
    "badgeType": "enchanted_tiara",
    "isFullyLoaded": true,
    "stage": 2,
    "color": "orange",
    "position": 8,
    "chestIndex": 2,
    "isMultiColored": false
  },
  "mpe_i_2_orange_8_3": {
    "chestId": "mpe_i_2_orange_8_3",
    "currentValue": 0,
    "maxValue": 14,
    "badgeType": "money_sack",
    "isFullyLoaded": true,
    "stage": 2,
    "color": "orange",
    "position": 8,
    "chestIndex": 3,
    "isMultiColored": false
  },
  "mpe_i_2_blue_8_1": {
    "chestId": "mpe_i_2_blue_8_1",
    "currentValue": 0,
    "maxValue": 17,
    "badgeType": "money_sack",
    "isFullyLoaded": true,
    "stage": 2,
    "color": "blue",
    "position": 8,
    "chestIndex": 1,
    "isMultiColored": false
  },
  "mpe_i_2_blue_8_2": {
    "chestId": "mpe_i_2_blue_8_2",
    "currentValue": 0,
    "maxValue": 9,
    "badgeType": "badge_farmers",
    "isFullyLoaded": true,
    "stage": 2,
    "color": "blue",
    "position": 8,
    "chestIndex": 2,
    "isMultiColored": false
  },
  "mpe_i_2_blue_8_3": {
    "chestId": "mpe_i_2_blue_8_3",
    "currentValue": 0,
    "maxValue": 29,
    "badgeType": "druid_staff",
    "isFullyLoaded": true,
    "stage": 2,
    "color": "blue",
    "position": 8,
    "chestIndex": 3,
    "isMultiColored": false
  },
  "mpe_i_2_green_8_1": {
    "chestId": "mpe_i_2_green_8_1",
    "currentValue": 0,
    "maxValue": 6,
    "badgeType": "badge_farmers",
    "isFullyLoaded": true,
    "stage": 2,
    "color": "green",
    "position": 8,
    "chestIndex": 1,
    "isMultiColored": false
  },
  "mpe_i_2_green_8_2": {
    "chestId": "mpe_i_2_green_8_2",
    "currentValue": 0,
    "maxValue": 11,
    "badgeType": "arcane_residue",
    "isFullyLoaded": true,
    "stage": 2,
    "color": "green",
    "position": 8,
    "chestIndex": 2,
    "isMultiColored": false
  },
  "mpe_i_2_green_8_3": {
    "chestId": "mpe_i_2_green_8_3",
    "currentValue": 0,
    "maxValue": 14,
    "badgeType": "badge_carpenters",
    "isFullyLoaded": true,
    "stage": 2,
    "color": "green",
    "position": 8,
    "chestIndex": 3,
    "isMultiColored": false
  },
  "mpe_i_2_orange_9_1": {
    "chestId": "mpe_i_2_orange_9_1",
    "currentValue": 0,
    "maxValue": 7,
    "badgeType": "druid_staff",
    "isFullyLoaded": true,
    "stage": 2,
    "color": "orange",
    "position": 9,
    "chestIndex": 1,
    "isMultiColored": false
  },
  "mpe_i_2_orange_9_2": {
    "chestId": "mpe_i_2_orange_9_2",
    "currentValue": 0,
    "maxValue": 7,
    "badgeType": "badge_carpenters",
    "isFullyLoaded": true,
    "stage": 2,
    "color": "orange",
    "position": 9,
    "chestIndex": 2,
    "isMultiColored": false
  },
  "mpe_i_2_orange_9_3": {
    "chestId": "mpe_i_2_orange_9_3",
    "currentValue": 0,
    "maxValue": 16,
    "badgeType": "arcane_residue",
    "isFullyLoaded": true,
    "stage": 2,
    "color": "orange",
    "position": 9,
    "chestIndex": 3,
    "isMultiColored": false
  },
  "mpe_i_2_blue_9_1": {
    "chestId": "mpe_i_2_blue_9_1",
    "currentValue": 0,
    "maxValue": 13,
    "badgeType": "diamond_necklace",
    "isFullyLoaded": true,
    "stage": 2,
    "color": "blue",
    "position": 9,
    "chestIndex": 1,
    "isMultiColored": false
  },
  "mpe_i_2_blue_9_2": {
    "chestId": "mpe_i_2_blue_9_2",
    "currentValue": 0,
    "maxValue": 13,
    "badgeType": "elegant_statue",
    "isFullyLoaded": true,
    "stage": 2,
    "color": "blue",
    "position": 9,
    "chestIndex": 2,
    "isMultiColored": false
  },
  "mpe_i_2_blue_9_3": {
    "chestId": "mpe_i_2_blue_9_3",
    "currentValue": 0,
    "maxValue": 4,
    "badgeType": "arcane_residue",
    "isFullyLoaded": true,
    "stage": 2,
    "color": "blue",
    "position": 9,
    "chestIndex": 3,
    "isMultiColored": false
  },
  "mpe_i_2_green_9_1": {
    "chestId": "mpe_i_2_green_9_1",
    "currentValue": 0,
    "maxValue": 7,
    "badgeType": "witch_hat",
    "isFullyLoaded": true,
    "stage": 2,
    "color": "green",
    "position": 9,
    "chestIndex": 1,
    "isMultiColored": false
  },
  "mpe_i_2_green_9_2": {
    "chestId": "mpe_i_2_green_9_2",
    "currentValue": 0,
    "maxValue": 4,
    "badgeType": "golden_bracelet",
    "isFullyLoaded": true,
    "stage": 2,
    "color": "green",
    "position": 9,
    "chestIndex": 2,
    "isMultiColored": false
  },
  "mpe_i_2_green_9_3": {
    "chestId": "mpe_i_2_green_9_3",
    "currentValue": 0,
    "maxValue": 6,
    "badgeType": "enchanted_tiara",
    "isFullyLoaded": true,
    "stage": 2,
    "color": "green",
    "position": 9,
    "chestIndex": 3,
    "isMultiColored": false
  },
  "mpe_i_3_stage_start_1": {
    "chestId": "mpe_i_3_stage_start_1",
    "currentValue": 0,
    "maxValue": 2,
    "badgeType": "badge_blacksmith",
    "isFullyLoaded": true,
    "stage": 3,
    "color": "start",
    "position": 0,
    "chestIndex": 1,
    "isMultiColored": false
  },
  "mpe_i_3_stage_start_2": {
    "chestId": "mpe_i_3_stage_start_2",
    "currentValue": 0,
    "maxValue": 2,
    "badgeType": "badge_farmers",
    "isFullyLoaded": true,
    "stage": 3,
    "color": "start",
    "position": 0,
    "chestIndex": 2,
    "isMultiColored": false
  },
  "mpe_i_3_orange_2_1": {
    "chestId": "mpe_i_3_orange_2_1",
    "currentValue": 0,
    "maxValue": 18,
    "badgeType": "witch_hat",
    "isFullyLoaded": true,
    "stage": 3,
    "color": "orange",
    "position": 2,
    "chestIndex": 1,
    "isMultiColored": false
  },
  "mpe_i_3_orange_2_2": {
    "chestId": "mpe_i_3_orange_2_2",
    "currentValue": 0,
    "maxValue": 8,
    "badgeType": "elegant_statue",
    "isFullyLoaded": true,
    "stage": 3,
    "color": "orange",
    "position": 2,
    "chestIndex": 2,
    "isMultiColored": false
  },
  "mpe_i_3_orange_2_3": {
    "chestId": "mpe_i_3_orange_2_3",
    "currentValue": 0,
    "maxValue": 37,
    "badgeType": "recycled_potion",
    "isFullyLoaded": true,
    "stage": 3,
    "color": "orange",
    "position": 2,
    "chestIndex": 3,
    "isMultiColored": false
  },
  "mpe_i_3_blue_2_1": {
    "chestId": "mpe_i_3_blue_2_1",
    "currentValue": 0,
    "maxValue": 51,
    "badgeType": "money_sack",
    "isFullyLoaded": true,
    "stage": 3,
    "color": "blue",
    "position": 2,
    "chestIndex": 1,
    "isMultiColored": false
  },
  "mpe_i_3_blue_2_2": {
    "chestId": "mpe_i_3_blue_2_2",
    "currentValue": 0,
    "maxValue": 9,
    "badgeType": "enchanted_tiara",
    "isFullyLoaded": true,
    "stage": 3,
    "color": "blue",
    "position": 2,
    "chestIndex": 2,
    "isMultiColored": false
  },
  "mpe_i_3_blue_2_3": {
    "chestId": "mpe_i_3_blue_2_3",
    "currentValue": 0,
    "maxValue": 38,
    "badgeType": "diamond_necklace",
    "isFullyLoaded": true,
    "stage": 3,
    "color": "blue",
    "position": 2,
    "chestIndex": 3,
    "isMultiColored": false
  },
  "mpe_i_3_green_2_1": {
    "chestId": "mpe_i_3_green_2_1",
    "currentValue": 0,
    "maxValue": 14,
    "badgeType": "badge_carpenters",
    "isFullyLoaded": true,
    "stage": 3,
    "color": "green",
    "position": 2,
    "chestIndex": 1,
    "isMultiColored": false
  },
  "mpe_i_3_green_2_2": {
    "chestId": "mpe_i_3_green_2_2",
    "currentValue": 0,
    "maxValue": 31,
    "badgeType": "druid_staff",
    "isFullyLoaded": true,
    "stage": 3,
    "color": "green",
    "position": 2,
    "chestIndex": 2,
    "isMultiColored": false
  },
  "mpe_i_3_green_2_3": {
    "chestId": "mpe_i_3_green_2_3",
    "currentValue": 0,
    "maxValue": 54,
    "badgeType": "ghost_in_a_bottle",
    "isFullyLoaded": true,
    "stage": 3,
    "color": "green",
    "position": 2,
    "chestIndex": 3,
    "isMultiColored": false
  },
  "mpe_i_3_orange_3_1": {
    "chestId": "mpe_i_3_orange_3_1",
    "currentValue": 0,
    "maxValue": 46,
    "badgeType": "badge_wonderhelper",
    "isFullyLoaded": true,
    "stage": 3,
    "color": "orange",
    "position": 3,
    "chestIndex": 1,
    "isMultiColored": true
  },
  "mpe_i_3_orange_3_2": {
    "chestId": "mpe_i_3_orange_3_2",
    "currentValue": 0,
    "maxValue": 46,
    "badgeType": "arcane_residue",
    "isFullyLoaded": true,
    "stage": 3,
    "color": "orange",
    "position": 3,
    "chestIndex": 2,
    "isMultiColored": true
  },
  "mpe_i_3_orange_3_3": {
    "chestId": "mpe_i_3_orange_3_3",
    "currentValue": 0,
    "maxValue": 8,
    "badgeType": "golden_bracelet",
    "isFullyLoaded": true,
    "stage": 3,
    "color": "orange",
    "position": 3,
    "chestIndex": 3,
    "isMultiColored": true
  },
  "mpe_i_3_blue_3_1": {
    "chestId": "mpe_i_3_blue_3_1",
    "currentValue": 0,
    "maxValue": 76,
    "badgeType": "elegant_statue",
    "isFullyLoaded": true,
    "stage": 3,
    "color": "blue",
    "position": 3,
    "chestIndex": 1,
    "isMultiColored": true
  },
  "mpe_i_3_blue_3_2": {
    "chestId": "mpe_i_3_blue_3_2",
    "currentValue": 0,
    "maxValue": 44,
    "badgeType": "badge_blacksmith",
    "isFullyLoaded": true,
    "stage": 3,
    "color": "blue",
    "position": 3,
    "chestIndex": 2,
    "isMultiColored": true
  },
  "mpe_i_3_blue_3_3": {
    "chestId": "mpe_i_3_blue_3_3",
    "currentValue": 0,
    "maxValue": 14,
    "badgeType": "ghost_in_a_bottle",
    "isFullyLoaded": true,
    "stage": 3,
    "color": "blue",
    "position": 3,
    "chestIndex": 3,
    "isMultiColored": true
  },
  "mpe_i_3_green_3_1": {
    "chestId": "mpe_i_3_green_3_1",
    "currentValue": 0,
    "maxValue": 32,
    "badgeType": "badge_blacksmith",
    "isFullyLoaded": true,
    "stage": 3,
    "color": "green",
    "position": 3,
    "chestIndex": 1,
    "isMultiColored": true
  },
  "mpe_i_3_green_3_2": {
    "chestId": "mpe_i_3_green_3_2",
    "currentValue": 0,
    "maxValue": 27,
    "badgeType": "diamond_necklace",
    "isFullyLoaded": true,
    "stage": 3,
    "color": "green",
    "position": 3,
    "chestIndex": 2,
    "isMultiColored": true
  },
  "mpe_i_3_green_3_3": {
    "chestId": "mpe_i_3_green_3_3",
    "currentValue": 0,
    "maxValue": 27,
    "badgeType": "badge_unit",
    "isFullyLoaded": true,
    "stage": 3,
    "color": "green",
    "position": 3,
    "chestIndex": 3,
    "isMultiColored": true
  },
  "mpe_i_3_orange_4_1": {
    "chestId": "mpe_i_3_orange_4_1",
    "currentValue": 0,
    "maxValue": 41,
    "badgeType": "money_sack",
    "isFullyLoaded": true,
    "stage": 3,
    "color": "orange",
    "position": 4,
    "chestIndex": 1,
    "isMultiColored": false
  },
  "mpe_i_3_orange_4_2": {
    "chestId": "mpe_i_3_orange_4_2",
    "currentValue": 0,
    "maxValue": 23,
    "badgeType": "badge_unit",
    "isFullyLoaded": true,
    "stage": 3,
    "color": "orange",
    "position": 4,
    "chestIndex": 2,
    "isMultiColored": false
  },
  "mpe_i_3_orange_4_3": {
    "chestId": "mpe_i_3_orange_4_3",
    "currentValue": 0,
    "maxValue": 40,
    "badgeType": "badge_blacksmith",
    "isFullyLoaded": true,
    "stage": 3,
    "color": "orange",
    "position": 4,
    "chestIndex": 3,
    "isMultiColored": false
  },
  "mpe_i_3_blue_4_1": {
    "chestId": "mpe_i_3_blue_4_1",
    "currentValue": 0,
    "maxValue": 25,
    "badgeType": "badge_farmers",
    "isFullyLoaded": true,
    "stage": 3,
    "color": "blue",
    "position": 4,
    "chestIndex": 1,
    "isMultiColored": false
  },
  "mpe_i_3_blue_4_2": {
    "chestId": "mpe_i_3_blue_4_2",
    "currentValue": 0,
    "maxValue": 32,
    "badgeType": "recycled_potion",
    "isFullyLoaded": true,
    "stage": 3,
    "color": "blue",
    "position": 4,
    "chestIndex": 2,
    "isMultiColored": false
  },
  "mpe_i_3_blue_4_3": {
    "chestId": "mpe_i_3_blue_4_3",
    "currentValue": 0,
    "maxValue": 95,
    "badgeType": "badge_brewery",
    "isFullyLoaded": true,
    "stage": 3,
    "color": "blue",
    "position": 4,
    "chestIndex": 3,
    "isMultiColored": false
  },
  "mpe_i_3_green_4_1": {
    "chestId": "mpe_i_3_green_4_1",
    "currentValue": 0,
    "maxValue": 18,
    "badgeType": "badge_farmers",
    "isFullyLoaded": true,
    "stage": 3,
    "color": "green",
    "position": 4,
    "chestIndex": 1,
    "isMultiColored": false
  },
  "mpe_i_3_green_4_2": {
    "chestId": "mpe_i_3_green_4_2",
    "currentValue": 0,
    "maxValue": 43,
    "badgeType": "witch_hat",
    "isFullyLoaded": true,
    "stage": 3,
    "color": "green",
    "position": 4,
    "chestIndex": 2,
    "isMultiColored": false
  },
  "mpe_i_3_green_4_3": {
    "chestId": "mpe_i_3_green_4_3",
    "currentValue": 0,
    "maxValue": 36,
    "badgeType": "golden_bracelet",
    "isFullyLoaded": true,
    "stage": 3,
    "color": "green",
    "position": 4,
    "chestIndex": 3,
    "isMultiColored": false
  },
  "mpe_i_3_orange_5_1": {
    "chestId": "mpe_i_3_orange_5_1",
    "currentValue": 0,
    "maxValue": 46,
    "badgeType": "arcane_residue",
    "isFullyLoaded": true,
    "stage": 3,
    "color": "orange",
    "position": 5,
    "chestIndex": 1,
    "isMultiColored": false
  },
  "mpe_i_3_orange_5_2": {
    "chestId": "mpe_i_3_orange_5_2",
    "currentValue": 0,
    "maxValue": 61,
    "badgeType": "enchanted_tiara",
    "isFullyLoaded": true,
    "stage": 3,
    "color": "orange",
    "position": 5,
    "chestIndex": 2,
    "isMultiColored": false
  },
  "mpe_i_3_orange_5_3": {
    "chestId": "mpe_i_3_orange_5_3",
    "currentValue": 0,
    "maxValue": 18,
    "badgeType": "witch_hat",
    "isFullyLoaded": true,
    "stage": 3,
    "color": "orange",
    "position": 5,
    "chestIndex": 3,
    "isMultiColored": false
  },
  "mpe_i_3_blue_5_1": {
    "chestId": "mpe_i_3_blue_5_1",
    "currentValue": 0,
    "maxValue": 9,
    "badgeType": "enchanted_tiara",
    "isFullyLoaded": true,
    "stage": 3,
    "color": "blue",
    "position": 5,
    "chestIndex": 1,
    "isMultiColored": false
  },
  "mpe_i_3_blue_5_2": {
    "chestId": "mpe_i_3_blue_5_2",
    "currentValue": 0,
    "maxValue": 76,
    "badgeType": "golden_bracelet",
    "isFullyLoaded": true,
    "stage": 3,
    "color": "blue",
    "position": 5,
    "chestIndex": 2,
    "isMultiColored": false
  },
  "mpe_i_3_blue_5_3": {
    "chestId": "mpe_i_3_blue_5_3",
    "currentValue": 0,
    "maxValue": 114,
    "badgeType": "badge_unit",
    "isFullyLoaded": true,
    "stage": 3,
    "color": "blue",
    "position": 5,
    "chestIndex": 3,
    "isMultiColored": false
  },
  "mpe_i_3_green_5_1": {
    "chestId": "mpe_i_3_green_5_1",
    "currentValue": 0,
    "maxValue": 14,
    "badgeType": "badge_carpenters",
    "isFullyLoaded": true,
    "stage": 3,
    "color": "green",
    "position": 5,
    "chestIndex": 1,
    "isMultiColored": false
  },
  "mpe_i_3_green_5_2": {
    "chestId": "mpe_i_3_green_5_2",
    "currentValue": 0,
    "maxValue": 72,
    "badgeType": "badge_wonderhelper",
    "isFullyLoaded": true,
    "stage": 3,
    "color": "green",
    "position": 5,
    "chestIndex": 2,
    "isMultiColored": false
  },
  "mpe_i_3_green_5_3": {
    "chestId": "mpe_i_3_green_5_3",
    "currentValue": 0,
    "maxValue": 98,
    "badgeType": "money_sack",
    "isFullyLoaded": true,
    "stage": 3,
    "color": "green",
    "position": 5,
    "chestIndex": 3,
    "isMultiColored": false
  },
  "mpe_i_3_orange_6_1": {
    "chestId": "mpe_i_3_orange_6_1",
    "currentValue": 0,
    "maxValue": 35,
    "badgeType": "diamond_necklace",
    "isFullyLoaded": true,
    "stage": 3,
    "color": "orange",
    "position": 6,
    "chestIndex": 1,
    "isMultiColored": true
  },
  "mpe_i_3_orange_6_2": {
    "chestId": "mpe_i_3_orange_6_2",
    "currentValue": 0,
    "maxValue": 23,
    "badgeType": "badge_farmers",
    "isFullyLoaded": true,
    "stage": 3,
    "color": "orange",
    "position": 6,
    "chestIndex": 2,
    "isMultiColored": true
  },
  "mpe_i_3_orange_6_3": {
    "chestId": "mpe_i_3_orange_6_3",
    "currentValue": 0,
    "maxValue": 46,
    "badgeType": "badge_wonderhelper",
    "isFullyLoaded": true,
    "stage": 3,
    "color": "orange",
    "position": 6,
    "chestIndex": 3,
    "isMultiColored": true
  },
  "mpe_i_3_blue_6_1": {
    "chestId": "mpe_i_3_blue_6_1",
    "currentValue": 0,
    "maxValue": 25,
    "badgeType": "badge_farmers",
    "isFullyLoaded": true,
    "stage": 3,
    "color": "blue",
    "position": 6,
    "chestIndex": 1,
    "isMultiColored": true
  },
  "mpe_i_3_blue_6_2": {
    "chestId": "mpe_i_3_blue_6_2",
    "currentValue": 0,
    "maxValue": 20,
    "badgeType": "arcane_residue",
    "isFullyLoaded": true,
    "stage": 3,
    "color": "blue",
    "position": 6,
    "chestIndex": 2,
    "isMultiColored": true
  },
  "mpe_i_3_blue_6_3": {
    "chestId": "mpe_i_3_blue_6_3",
    "currentValue": 0,
    "maxValue": 44,
    "badgeType": "badge_blacksmith",
    "isFullyLoaded": true,
    "stage": 3,
    "color": "blue",
    "position": 6,
    "chestIndex": 3,
    "isMultiColored": true
  },
  "mpe_i_3_green_6_1": {
    "chestId": "mpe_i_3_green_6_1",
    "currentValue": 0,
    "maxValue": 18,
    "badgeType": "enchanted_tiara",
    "isFullyLoaded": true,
    "stage": 3,
    "color": "green",
    "position": 6,
    "chestIndex": 1,
    "isMultiColored": true
  },
  "mpe_i_3_green_6_2": {
    "chestId": "mpe_i_3_green_6_2",
    "currentValue": 0,
    "maxValue": 27,
    "badgeType": "diamond_necklace",
    "isFullyLoaded": true,
    "stage": 3,
    "color": "green",
    "position": 6,
    "chestIndex": 2,
    "isMultiColored": true
  },
  "mpe_i_3_green_6_3": {
    "chestId": "mpe_i_3_green_6_3",
    "currentValue": 0,
    "maxValue": 72,
    "badgeType": "recycled_potion",
    "isFullyLoaded": true,
    "stage": 3,
    "color": "green",
    "position": 6,
    "chestIndex": 3,
    "isMultiColored": true
  },
  "mpe_i_3_orange_7_1": {
    "chestId": "mpe_i_3_orange_7_1",
    "currentValue": 0,
    "maxValue": 77,
    "badgeType": "badge_brewery",
    "isFullyLoaded": true,
    "stage": 3,
    "color": "orange",
    "position": 7,
    "chestIndex": 1,
    "isMultiColored": false
  },
  "mpe_i_3_orange_7_2": {
    "chestId": "mpe_i_3_orange_7_2",
    "currentValue": 0,
    "maxValue": 41,
    "badgeType": "money_sack",
    "isFullyLoaded": true,
    "stage": 3,
    "color": "orange",
    "position": 7,
    "chestIndex": 2,
    "isMultiColored": false
  },
  "mpe_i_3_orange_7_3": {
    "chestId": "mpe_i_3_orange_7_3",
    "currentValue": 0,
    "maxValue": 20,
    "badgeType": "druid_staff",
    "isFullyLoaded": true,
    "stage": 3,
    "color": "orange",
    "position": 7,
    "chestIndex": 3,
    "isMultiColored": false
  },
  "mpe_i_3_blue_7_1": {
    "chestId": "mpe_i_3_blue_7_1",
    "currentValue": 0,
    "maxValue": 86,
    "badgeType": "druid_staff",
    "isFullyLoaded": true,
    "stage": 3,
    "color": "blue",
    "position": 7,
    "chestIndex": 1,
    "isMultiColored": false
  },
  "mpe_i_3_blue_7_2": {
    "chestId": "mpe_i_3_blue_7_2",
    "currentValue": 0,
    "maxValue": 36,
    "badgeType": "badge_carpenters",
    "isFullyLoaded": true,
    "stage": 3,
    "color": "blue",
    "position": 7,
    "chestIndex": 2,
    "isMultiColored": false
  },
  "mpe_i_3_blue_7_3": {
    "chestId": "mpe_i_3_blue_7_3",
    "currentValue": 0,
    "maxValue": 51,
    "badgeType": "money_sack",
    "isFullyLoaded": true,
    "stage": 3,
    "color": "blue",
    "position": 7,
    "chestIndex": 3,
    "isMultiColored": false
  },
  "mpe_i_3_green_7_1": {
    "chestId": "mpe_i_3_green_7_1",
    "currentValue": 0,
    "maxValue": 32,
    "badgeType": "badge_blacksmith",
    "isFullyLoaded": true,
    "stage": 3,
    "color": "green",
    "position": 7,
    "chestIndex": 1,
    "isMultiColored": false
  },
  "mpe_i_3_green_7_2": {
    "chestId": "mpe_i_3_green_7_2",
    "currentValue": 0,
    "maxValue": 27,
    "badgeType": "badge_unit",
    "isFullyLoaded": true,
    "stage": 3,
    "color": "green",
    "position": 7,
    "chestIndex": 2,
    "isMultiColored": false
  },
  "mpe_i_3_green_7_3": {
    "chestId": "mpe_i_3_green_7_3",
    "currentValue": 0,
    "maxValue": 31,
    "badgeType": "druid_staff",
    "isFullyLoaded": true,
    "stage": 3,
    "color": "green",
    "position": 7,
    "chestIndex": 3,
    "isMultiColored": false
  },
  "mpe_i_3_orange_8_1": {
    "chestId": "mpe_i_3_orange_8_1",
    "currentValue": 0,
    "maxValue": 42,
    "badgeType": "badge_carpenters",
    "isFullyLoaded": true,
    "stage": 3,
    "color": "orange",
    "position": 8,
    "chestIndex": 1,
    "isMultiColored": false
  },
  "mpe_i_3_orange_8_2": {
    "chestId": "mpe_i_3_orange_8_2",
    "currentValue": 0,
    "maxValue": 92,
    "badgeType": "ghost_in_a_bottle",
    "isFullyLoaded": true,
    "stage": 3,
    "color": "orange",
    "position": 8,
    "chestIndex": 2,
    "isMultiColored": false
  },
  "mpe_i_3_orange_8_3": {
    "chestId": "mpe_i_3_orange_8_3",
    "currentValue": 0,
    "maxValue": 37,
    "badgeType": "recycled_potion",
    "isFullyLoaded": true,
    "stage": 3,
    "color": "orange",
    "position": 8,
    "chestIndex": 3,
    "isMultiColored": false
  },
  "mpe_i_3_blue_8_1": {
    "chestId": "mpe_i_3_blue_8_1",
    "currentValue": 0,
    "maxValue": 14,
    "badgeType": "ghost_in_a_bottle",
    "isFullyLoaded": true,
    "stage": 3,
    "color": "blue",
    "position": 8,
    "chestIndex": 1,
    "isMultiColored": false
  },
  "mpe_i_3_blue_8_2": {
    "chestId": "mpe_i_3_blue_8_2",
    "currentValue": 0,
    "maxValue": 51,
    "badgeType": "badge_wonderhelper",
    "isFullyLoaded": true,
    "stage": 3,
    "color": "blue",
    "position": 8,
    "chestIndex": 2,
    "isMultiColored": false
  },
  "mpe_i_3_blue_8_3": {
    "chestId": "mpe_i_3_blue_8_3",
    "currentValue": 0,
    "maxValue": 32,
    "badgeType": "recycled_potion",
    "isFullyLoaded": true,
    "stage": 3,
    "color": "blue",
    "position": 8,
    "chestIndex": 3,
    "isMultiColored": false
  },
  "mpe_i_3_green_8_1": {
    "chestId": "mpe_i_3_green_8_1",
    "currentValue": 0,
    "maxValue": 90,
    "badgeType": "badge_brewery",
    "isFullyLoaded": true,
    "stage": 3,
    "color": "green",
    "position": 8,
    "chestIndex": 1,
    "isMultiColored": false
  },
  "mpe_i_3_green_8_2": {
    "chestId": "mpe_i_3_green_8_2",
    "currentValue": 0,
    "maxValue": 18,
    "badgeType": "badge_farmers",
    "isFullyLoaded": true,
    "stage": 3,
    "color": "green",
    "position": 8,
    "chestIndex": 2,
    "isMultiColored": false
  },
  "mpe_i_3_green_8_3": {
    "chestId": "mpe_i_3_green_8_3",
    "currentValue": 0,
    "maxValue": 36,
    "badgeType": "elegant_statue",
    "isFullyLoaded": true,
    "stage": 3,
    "color": "green",
    "position": 8,
    "chestIndex": 3,
    "isMultiColored": false
  },
  "mpe_i_3_orange_9_1": {
    "chestId": "mpe_i_3_orange_9_1",
    "currentValue": 0,
    "maxValue": 8,
    "badgeType": "golden_bracelet",
    "isFullyLoaded": true,
    "stage": 3,
    "color": "orange",
    "position": 9,
    "chestIndex": 1,
    "isMultiColored": false
  },
  "mpe_i_3_orange_9_2": {
    "chestId": "mpe_i_3_orange_9_2",
    "currentValue": 0,
    "maxValue": 8,
    "badgeType": "elegant_statue",
    "isFullyLoaded": true,
    "stage": 3,
    "color": "orange",
    "position": 9,
    "chestIndex": 2,
    "isMultiColored": false
  },
  "mpe_i_3_orange_9_3": {
    "chestId": "mpe_i_3_orange_9_3",
    "currentValue": 0,
    "maxValue": 20,
    "badgeType": "druid_staff",
    "isFullyLoaded": true,
    "stage": 3,
    "color": "orange",
    "position": 9,
    "chestIndex": 3,
    "isMultiColored": false
  },
  "mpe_i_3_blue_9_1": {
    "chestId": "mpe_i_3_blue_9_1",
    "currentValue": 0,
    "maxValue": 20,
    "badgeType": "arcane_residue",
    "isFullyLoaded": true,
    "stage": 3,
    "color": "blue",
    "position": 9,
    "chestIndex": 1,
    "isMultiColored": false
  },
  "mpe_i_3_blue_9_2": {
    "chestId": "mpe_i_3_blue_9_2",
    "currentValue": 0,
    "maxValue": 38,
    "badgeType": "diamond_necklace",
    "isFullyLoaded": true,
    "stage": 3,
    "color": "blue",
    "position": 9,
    "chestIndex": 2,
    "isMultiColored": false
  },
  "mpe_i_3_blue_9_3": {
    "chestId": "mpe_i_3_blue_9_3",
    "currentValue": 0,
    "maxValue": 46,
    "badgeType": "witch_hat",
    "isFullyLoaded": true,
    "stage": 3,
    "color": "blue",
    "position": 9,
    "chestIndex": 3,
    "isMultiColored": false
  },
  "mpe_i_3_green_9_1": {
    "chestId": "mpe_i_3_green_9_1",
    "currentValue": 0,
    "maxValue": 14,
    "badgeType": "badge_carpenters",
    "isFullyLoaded": true,
    "stage": 3,
    "color": "green",
    "position": 9,
    "chestIndex": 1,
    "isMultiColored": false
  },
  "mpe_i_3_green_9_2": {
    "chestId": "mpe_i_3_green_9_2",
    "currentValue": 0,
    "maxValue": 18,
    "badgeType": "enchanted_tiara",
    "isFullyLoaded": true,
    "stage": 3,
    "color": "green",
    "position": 9,
    "chestIndex": 2,
    "isMultiColored": false
  },
  "mpe_i_3_green_9_3": {
    "chestId": "mpe_i_3_green_9_3",
    "currentValue": 0,
    "maxValue": 63,
    "badgeType": "arcane_residue",
    "isFullyLoaded": true,
    "stage": 3,
    "color": "green",
    "position": 9,
    "chestIndex": 3,
    "isMultiColored": false
  }
};
  